const FETCH_PHONES_REQUEST = "FETCH_PHONES_REQUEST";
const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
const FETCH_PHONES_FAILURE = "FETCH_PHONES_FAILURE";

export { FETCH_PHONES_FAILURE, FETCH_PHONES_REQUEST, FETCH_PHONES_SUCCESS };
