const FETCH_PHONES_REQUEST = "FETCH_PHONES_REQUEST";
const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
const FETCH_PHONES_FAILURE = "FETCH_PHONES_FAILURE";

const LOAD_MORE_PHONES_REQUEST = "LOAD_MORE_PHONES_REQUEST";
const LOAD_MORE_PHONES_SUCCESS = "LOAD_MORE_PHONES_SUCCESS";
const LOAD_MORE_PHONES_FAILURE = "LOAD_MORE_PHONES_FAILURE";

const FETCH_PHONE_BY_ID_REQUEST = "FETCH_PHONE_BY_ID_REQUEST";
const FETCH_PHONE_BY_ID_SUCCESS = "FETCH_PHONE_BY_ID_SUCCESS";
const FETCH_PHONE_BY_ID_FAILURE = "FETCH_PHONE_BY_ID_FAILURE";

const ADD_PHONE_TO_CART = "ADD_PHONE_TO_CART";

const SEARCH_PHONES = "SEARCH_PHONES";

export {
  FETCH_PHONES_FAILURE,
  FETCH_PHONES_REQUEST,
  FETCH_PHONES_SUCCESS,
  LOAD_MORE_PHONES_FAILURE,
  LOAD_MORE_PHONES_REQUEST,
  LOAD_MORE_PHONES_SUCCESS,
  FETCH_PHONE_BY_ID_FAILURE,
  FETCH_PHONE_BY_ID_REQUEST,
  FETCH_PHONE_BY_ID_SUCCESS,
  ADD_PHONE_TO_CART,
  SEARCH_PHONES
};
