const FETCH_PHONES_REQUEST = "FETCH_PHONES_REQUEST";
const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
const FETCH_PHONES_FAILURE = "FETCH_PHONES_FAILURE";

const LOAD_MORE_PHONES_REQUEST = "LOAD_MORE_PHONES_REQUEST";
const LOAD_MORE_PHONES_SUCCESS = "LOAD_MORE_PHONES_SUCCESS";
const LOAD_MORE_PHONES_FAILURE = "LOAD_MORE_PHONES_FAILURE";

export {
  FETCH_PHONES_FAILURE,
  FETCH_PHONES_REQUEST,
  FETCH_PHONES_SUCCESS,
  LOAD_MORE_PHONES_FAILURE,
  LOAD_MORE_PHONES_REQUEST,
  LOAD_MORE_PHONES_SUCCESS
};
